### ISSUE TITLE
让gif动起来！

### ISSUE THREAD

**Issue by wangjiafei2000** [tccoin/klog2.0#32]
我上传的动态gif在文章中变成了静态（就是klog的问题！）。找到上传至storage.krrr.party的位置看到的也是动态gif，不知能否加入上传动态gif的功能。

**Comment by tccoin** [comment]
因为gif格式效率比较低，所以不推荐使用，所有图像都会在传输前转成jpeg/webp格式，所以gif不会动了。建议把动画转成mp4上传，然后手动把markdown改成和图片一样的语法。比如：
```
![some video](123.mp4)
```

**Comment by wangjiafei2000** [comment]
ok

**Comment by tccoin** [comment]
7c2896b 已经部署了，现在上传mp4格式的视频会直接以正确的语法插入文章显示出来。
